final List<Map<String, dynamic>> challengeSeeds = [
  {
    'id': 1,
    'date': DateTime.now().toIso8601String(),
    'title': 'Trinke 2 Liter Wasser',
    'description': 'Die ausreichende Flüssigkeitszufuhr ist entscheidend für die Aufrechterhaltung einer optimalen Körperfunktion. Wasser spielt eine wichtige Rolle bei der Regulierung der Körpertemperatur, der Verdauung, der Nährstoffaufnahme und der Beseitigung von Abfallstoffen. Es fördert auch die Hautgesundheit und hilft, das Energieniveau zu erhalten.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "400ml", 2: "800ml", 3: "1.2L", 4: "1.6L", 5: "2L"}',
    'userProgress': 0,
  },
  {
    'id': 2,
    'date': DateTime.now().add(const Duration(days: 1)).toIso8601String(),
    'title': 'Mache 30 Minuten Cardio-Training',
    'description': 'Das regelmäßige Cardio-Training über 30 Minuten fördert die Herzgesundheit und verbessert die Ausdauer. Es erhöht den Herzschlag und verbessert die Durchblutung, was zur Stärkung des Herz-Kreislauf-Systems beiträgt. Darüber hinaus unterstützt Cardio-Training die Gewichtsabnahme, verbessert den Stoffwechsel und fördert das allgemeine Wohlbefinden.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "6 min", 2: "12 min", 3: "18 min", 4: "24 min", 5: "30 min"}',
    'userProgress': 0,
  },
  {
    'id': 3,
    'date': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
    'title': 'Iss 5 Portionen Obst und Gemüse',
    'description': 'Der regelmäßige Verzehr von fünf Portionen Obst und Gemüse trägt wesentlich zur Aufrechterhaltung einer ausgewogenen Ernährung und eines gesunden Lebensstils bei. Obst und Gemüse sind reich an lebenswichtigen Vitaminen, Mineralstoffen und Ballaststoffen, die die Immunfunktion stärken, Entzündungen reduzieren und das Risiko von chronischen Krankheiten wie Herzerkrankungen, Diabetes und einigen Krebsarten verringern können. Durch den Konsum verschiedener Arten und Farben von Obst und Gemüse erhält der Körper eine breite Palette von Nährstoffen, die für die allgemeine Gesundheit und das Wohlbefinden von großer Bedeutung sind.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "1", 2: "2", 3: "3", 4: "4", 5: "5"}',
    'userProgress': 0,
  },
  {
    'id': 4,
    'date': DateTime.now().add(const Duration(days: 3)).toIso8601String(),
    'title': 'Mache 15 Minuten Dehnübungen',
    'description': 'Das regelmäßige Durchführen von 15-minütigen Dehnübungen trägt zur Verbesserung der Flexibilität und Beweglichkeit bei. Dehnübungen helfen, die Muskeln zu entspannen, die Durchblutung zu verbessern und die Gelenkbeweglichkeit zu erhöhen. Sie tragen dazu bei, Muskelverspannungen zu lösen und das Verletzungsrisiko während körperlicher Aktivitäten zu verringern. Zudem können sie zur Förderung der Körperhaltung und zur Verringerung von Stress beitragen.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "3 min", 2: "6 min", 3: "9 min", 4: "12 min", 5: "15 min"}',
    'userProgress': 0,
  },
  {
    'id': 5,
    'date': DateTime.now().add(const Duration(days: 4)).toIso8601String(),
    'title': 'Schlafe 8 Stunden',
    'description': 'Ausreichender und qualitativ hochwertiger Schlaf über 8 Stunden ist für die Regeneration des Körpers und des Geistes von entscheidender Bedeutung. Während des Schlafs durchlaufen wir verschiedene Schlafzyklen, die für die körperliche Erholung, die Konsolidierung des Gedächtnisses und die Aufrechterhaltung eines gesunden Stoffwechsels wichtig sind. Der Schlaf spielt eine zentrale Rolle bei der Regulierung des Hormonhaushalts, der Stärkung des Immunsystems und der Förderung des allgemeinen Wohlbefindens.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "4", 2: "5", 3: "6", 4: "7", 5: "8"}',
    'userProgress': 0,
  },
  {
    'id': 6,
    'date': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
    'title': 'Mache 30 Minuten Krafttraining',
    'description': 'Regelmäßiges Krafttraining über 30 Minuten hilft dabei, Muskelmasse aufzubauen, die Knochendichte zu erhöhen und die Körperhaltung zu verbessern. Krafttraining stärkt nicht nur die Muskeln, sondern trägt auch dazu bei, den Stoffwechsel zu steigern, was wiederum zur Verbrennung von Kalorien beiträgt. Darüber hinaus kann Krafttraining dazu beitragen, das Verletzungsrisiko im Alltag zu verringern und die allgemeine körperliche Leistungsfähigkeit zu verbessern.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "6 min", 2: "12 min", 3: "18 min", 4: "24 min", 5: "30 min"}',
    'userProgress': 0,
  },
  {
    'id': 7,
    'date': DateTime.now().add(const Duration(days: 6)).toIso8601String(),
    'title': 'Mache 10 Minuten Meditation oder Atemübungen',
    'description': 'Das regelmäßige Praktizieren von 10-minütiger Meditation oder Atemübungen trägt zur Förderung von Entspannung, Stressabbau und emotionaler Ausgeglichenheit bei. Meditation und Atemübungen können dazu beitragen, den Geist zu beruhigen, die Konzentration zu verbessern und das allgemeine Wohlbefinden zu steigern. Durch die Fokussierung auf die Atmung und das bewusste Beobachten der Gedanken können Sie Ihre Stressreaktionen kontrollieren und Ihre geistige Klarheit fördern.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "2", 2: "4", 3: "6", 4: "8", 5: "10"}',
    'userProgress': 0,
  },
  {
    'id': 8,
    'date': DateTime.now().add(const Duration(days: 7)).toIso8601String(),
    'title': 'Verzichte auf Fast Food und Süßigkeiten',
    'description': 'Der Verzicht auf Fast Food und Süßigkeiten trägt erheblich zur Förderung einer ausgewogenen Ernährung und zur Verbesserung der allgemeinen Gesundheit bei. Fast Food und Süßigkeiten enthalten oft hohe Mengen an gesättigten Fettsäuren, Zucker und Kalorien, die mit einem erhöhten Risiko für Fettleibigkeit, Herzerkrankungen und Diabetes in Verbindung gebracht werden. Durch den Verzicht auf diese ungesunden Lebensmittel können Sie Ihren Blutzuckerspiegel stabilisieren, die Gewichtskontrolle erleichtern und das Risiko von ernährungsbedingten Krankheiten verringern.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "6h", 2: "12h", 3: "18h", 4: "24h"}',
    'userProgress': 0,
  },
  {
    'id': 9,
    'date': DateTime.now().add(const Duration(days: 8)).toIso8601String(),
    'title': 'Gehe 10.000 Schritte',
    'description': 'Das Erreichen von 10.000 Schritten pro Tag ist ein wichtiger Beitrag zur Aufrechterhaltung eines aktiven Lebensstils und zur Förderung der allgemeinen körperlichen Gesundheit. Regelmäßige körperliche Aktivität, wie das Gehen, trägt zur Stärkung des Herz-Kreislauf-Systems, zur Verbesserung der Ausdauer und zur Förderung eines gesunden Körpergewichts bei. Durch das Erreichen dieses Schrittziels können Sie auch Ihre Stimmung verbessern und das allgemeine Wohlbefinden steigern.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "2.000", 2: "4.000", 3: "6.000", 4: "8.000", 5: "10.000"}',
    'userProgress': 0,
  },
  {
    'id': 10,
    'date': DateTime.now().add(const Duration(days: 9)).toIso8601String(),
    'title': 'Mache 30 Minuten HIIT-Training',
    'description': 'Das regelmäßige 30-minütige HIIT-Training (High Intensity Interval Training) ist eine effektive Methode, um die aerobe Fitness zu steigern, Kalorien zu verbrennen und die Muskelkraft zu verbessern. HIIT kombiniert intensive Intervalle mit kurzen Erholungsphasen, um den Stoffwechsel anzukurbeln und den Nachbrenneffekt zu maximieren, was zu einer erhöhten Fettverbrennung und einem verbesserten Herz-Kreislauf-System führt. Es kann auch dabei helfen, die Ausdauer zu verbessern und die Muskelmasse zu erhalten.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "6 min", 2: "12 min", 3: "18 min", 4: "24 min", 5: "30 min"}',
    'userProgress': 0,
  },
  {
    'id': 11,
    'date': DateTime.now().add(const Duration(days: 10)).toIso8601String(),
    'title': 'Koche zu Hause anstatt auswärts zu essen',
    'description': 'Das Zubereiten von Mahlzeiten zu Hause anstelle des Essens außerhalb des Hauses trägt erheblich zur Förderung einer gesunden Ernährung und einer besseren Kontrolle über die Zutaten und Portionsgrößen bei. Das Kochen zu Hause ermöglicht es, frische und nährstoffreiche Zutaten zu verwenden und den Konsum von ungesunden Zusatzstoffen, gesättigten Fettsäuren und übermäßigem Salz zu reduzieren. Durch das Kochen zu Hause können Sie auch die Qualität Ihrer Mahlzeiten kontrollieren und gesündere Zubereitungsmethoden wie Dämpfen, Braten oder Backen anwenden.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "1"}',
    'userProgress': 0,
  },
  {
    'id': 12,
    'date': DateTime.now().add(const Duration(days: 11)).toIso8601String(),
    'title': 'Probiere eine neue Obstsorte',
    'description': 'Das Ausprobieren einer neuen Obstsorte ist eine großartige Möglichkeit, die Vielfalt in Ihrer Ernährung zu erhöhen und von einer breiteren Palette von Nährstoffen zu profitieren. Unterschiedliche Obstsorten bieten unterschiedliche Vitamine, Mineralien und Antioxidantien, die zur Stärkung des Immunsystems, zur Förderung der Verdauung und zur Unterstützung der allgemeinen Gesundheit beitragen können. Durch das Ausprobieren neuer Obstsorten können Sie auch Ihren Geschmackshorizont erweitern und die Freude am Essen steigern.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "1"}',
    'userProgress': 0,
  },
  {
    'id': 13,
    'date': DateTime.now().add(const Duration(days: 12)).toIso8601String(),
    'title': 'Verzehre eine Mahlzeit ohne Ablenkung durch elektronische Geräte',
    'description': 'Das Verzehren einer Mahlzeit ohne Ablenkung durch elektronische Geräte fördert bewusstes Essen und verbessert die Wahrnehmung von Geschmack, Textur und Sättigung. Indem Sie sich auf Ihre Mahlzeit konzentrieren und Ablenkungen wie Fernsehen, Handys oder Computer vermeiden, können Sie besser auf Ihr Sättigungsgefühl achten und eine gesündere Portionskontrolle praktizieren. Dadurch können Sie das Esserlebnis verbessern und sich bewusster mit den Nahrungsmitteln und deren Einfluss auf Ihren Körper auseinandersetzen.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "1"}',
    'userProgress': 0,
  },
  {
    'id': 14,
    'date': DateTime.now().add(const Duration(days: 13)).toIso8601String(),
    'title': 'Führe 10 Minuten Haltungskorrekturen durch',
    'description': 'Das regelmäßige Durchführen von 10-minütigen Haltungskorrekturen kann dazu beitragen, Rückenschmerzen zu reduzieren, die Körperhaltung zu verbessern und das Risiko von Verletzungen im Zusammenhang mit einer schlechten Körperhaltung zu verringern. Haltungskorrekturen beinhalten das gezielte Training und die Stärkung der Muskelgruppen, die für eine aufrechte und stabile Körperhaltung wichtig sind, wie beispielsweise die Bauchmuskeln, den unteren Rücken und die Schultern. Dies kann zu einer verbesserten Wirbelsäulengesundheit, einer besseren Atmung und einem gesteigerten Selbstbewusstsein führen.',
    'explanation': '',
    'category': 'Sport',
    'progress': '{1: "2 min", 2: "4 min", 3: "6 min", 4: "8 min", 5: "10 min"}',
    'userProgress': 0,
  },
  {
    'id': 15,
    'date': DateTime.now().add(const Duration(days: 14)).toIso8601String(),
    'title': 'Ersetze raffiniertes Mehl durch Vollkornprodukte',
    'description': 'Der Ersatz von raffiniertem Mehl durch Vollkornprodukte ist eine gesunde Ernährungsgewohnheit, die zu einer verbesserten Nährstoffaufnahme und einer besseren Regulation des Blutzuckerspiegels beitragen kann. Vollkornprodukte enthalten mehr Ballaststoffe, Vitamine und Mineralien im Vergleich zu raffinierten Mehlen, die während des Verarbeitungsprozesses an Nährstoffen verlieren. Durch den Verzehr von Vollkornprodukten können Sie die Verdauung fördern, das Sättigungsgefühl erhöhen und das Risiko von Herzerkrankungen, Diabetes und einigen Krebsarten verringern.',
    'explanation': '',
    'category': 'Nutrition',
    'progress': '{1: "1"}',
    'userProgress': 0,
  }
];
